### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by a-ja** [NicolasStr/gmod-roleplayjobsystem#1]
[ERROR] addons/gmod-roleplayjobsystem-master/lua/autorun/client/cl_rpjsloader.lua:17: attempt to concatenate field 'version' (a nil value)
  1. unknown - addons/gmod-roleplayjobsystem-master/lua/autorun/client/cl_rpjsloader.lua:17
 Plz help if its not a hassle :)

**Comment by NicolasStr** [comment]
Issue fixed in [v1.9](https://github.com/NicolasStr/gmod-roleplayjobsystem/releases/tag/v1.9)

Thanks for report !
