### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Squidplay** [NicolasStr/gmod-roleplayjobsystem#4]
sorry if my english is bad :c --- I just installed the addon on my server, I have everything ok, except that I see the npc as an error
![imagen](https://user-images.githubusercontent.com/63181265/78468095-72e11580-76ea-11ea-844c-43a6efb061b9.png)

**Comment by Squidplay** [comment]
I installed it where it should go

**Comment by NicolasStr** [comment]
Hello,
Did you correctly add the prop with !rpjs ? (or rpjs_spawn in console)

**Comment by Squidplay** [comment]
Yes i did

**Comment by NicolasStr** [comment]
do you have any log/error somewhere ?

**Comment by NicolasStr** [comment]
If you didn't change anything in the files, please run `rpjs_debug` in you console and paste here the output.

**Comment by Squidplay** [comment]
1.Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)

2.[ERROR] addons/roleplay job system/lua/rpjs/sv_lib.lua:38: attempt to index field 'loaded' (a nil value)
  1. unknown - addons/roleplay job system/lua/rpjs/sv_lib.lua:38
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by Squidplay** [comment]
the first text appears when spawning the npc, the second text appears when I type the rpjs_debug in the console

**Comment by NicolasStr** [comment]
I fixed the bug, could you please update to the realase v1.9.1 ?

https://github.com/NicolasStr/gmod-roleplayjobsystem/releases/tag/v1.9.1

Please update and recheck rpjs_debug.

thank you

**Comment by Squidplay** [comment]
omg thx, pd: i love this addon :)

**Comment by Squidplay** [comment]
nvm, it says this with any model, i have css mounted if you ask. this time i tried with gman.

missing model: "models/player/gman_high.mdl"

**Comment by NicolasStr** [comment]
Please reply with the output of rpjs_debug into the console.
